### ISSUE TITLE
RuntimeError: No Cloud Controller Admin URL specified in the configuration file.

### ISSUE THREAD

**Issue by zioproto** [icclab/hurtle_sm#1]
The example config give this reference line:

`nb_api=http://cc.cloudcomplab.ch:8889`
but you will get this error

```
ubuntu@wp3-service-manager:~$ service_manager -c /home/ubuntu/disco/etc/sm.cfg
/usr/lib/python2.7/dist-packages/pkg_resources.py:1031: UserWarning: /home/ubuntu/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Using CONFIG_PATH /home/ubuntu/disco/etc/sm.cfg
Traceback (most recent call last):
  File "/usr/local/bin/service_manager", line 5, in <module>
    pkg_resources.run_script('sm==0.4', 'service_manager')
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 528, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 1394, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/sm-0.4-py2.7.egg/EGG-INFO/scripts/service_manager", line 22, in <module>
    from sm import admin
  File "/usr/local/lib/python2.7/dist-packages/sm-0.4-py2.7.egg/sm/admin.py", line 29, in <module>
    raise RuntimeError('No Cloud Controller Admin URL specified in the configuration file.')
RuntimeError: No Cloud Controller Admin URL specified in the configuration file.
ubuntu@wp3-service-manager:~$ service_manager -c /home/ubuntu/disco/etc/sm.cfg
```

I think it expects something like

`nb_admin_api=http://cc.cloudcomplab.ch:8889`

Please clarify in the reference template file for configuration.

**Comment by zioproto** [comment]
@Pentadactylus !!! can you fix this ? :)

**Comment by michaelerne** [comment]
I'll update a example config tomorrow morning. We are currently adding CI/CD features on the master branch, if you want something more 'stable', use the released version.

**Comment by zioproto** [comment]
@Pentadactylus we cloned the wrong version from github ? We need to checkout a specific branch ?

**Comment by Pentadactylus** [comment]
@zioproto yes, I had no idea about this change. I just tried it on a local instance with the last released version and the SM is working. Though I need to check which parameters have to be provided to the DISCO SM so that it's working out of the box.

**Comment by michaelerne** [comment]
359278cd99194dd3b91fd0d22794a84767ea838e adds some example parameters in the config file. The fix for issue #2 also prevents the SM from crashing if parameters are missing. Let me know if that works for you.

**Comment by michaelerne** [comment]
@zioproto any updates?

**Comment by zioproto** [comment]
I used the stable tag with @Pentadactylus and we managed to go further.
